program: exp/run.py
method: random
metric:
  name: val_acc
  goal: maximize
parameters:
  model:
    distribution: constant
    value: "IdentitySheaf"
  d:
    distribution: categorical
    value: [1, 2]
  add_lp:
    distribution: constant
    values: 0
  add_hp:
    distribution: categorical
    values: [1, 0]
  dataset:
    distribution: constant
    value: 'chameleon'
  layers:
    distribution: categorical
    values: [4, 5, 6, 7]
  hidden_channels:
    distribution: categorical
    values: [64, 128, 256]
  weight_decay:
    distribution: log_uniform
    min: -11.0
    max: -4.5
  sheaf_decay:
    distribution: log_uniform
    min: -11.0
    max: -4.5
  input_dropout:
    distribution: categorical
    values: [0.7, 0.8, 0.9]
  dropout:
    distribution: categorical
    values: [0.0, 0.1]
  lr:
    distribution: categorical
    value: [0.01, 0.005]
  epochs:
    distribution: constant
    value: 400
  early_stopping:
    distribution: constant
    value: 50
  folds:
    distribution: constant
    value: 3
  orth:
    distribution: constant
    value: "householder"
command:
  - ${env}
  - python3
  - ${program}
  - ${args}
  - --left_weights=True
  - --right_weights=True
  - --use_act=True
  - --normalised=True
  - --edge_weights=True
  - --entity=${ENTITY}